# Generated by Django 5.0.3 on 2024-04-09 18:34

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="background_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.files.upload_path,
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="external_link",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
