# Generated by Django 5.0.3 on 2024-03-23 09:07

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(upload_to=utils.files.upload_path, verbose_name='Логотип партнёра'),
        ),
    ]
