# Generated by Django 5.0.3 on 2024-03-23 10:49

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0002_alter_partner_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название рейтинга')),
                ('logo', models.FileField(upload_to=utils.files.upload_path, verbose_name='Логотип рейтинга')),
            ],
            options={
                'verbose_name': 'Упоминание в рейтинге',
                'verbose_name_plural': 'Упоминания в рейтингах',
            },
        ),
    ]
