# Generated by Django 4.0.6 on 2024-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperation', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='link',
            field=models.CharField(max_length=1024, null=True, verbose_name='Ссылка на рейтинг'),
        ),
    ]
