# Generated by Django 5.0.3 on 2024-03-23 08:49

import avantage_backend.blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Название статьи (Ru)')),
                ('title_en', models.CharField(max_length=512, verbose_name='Название статьи (En)')),
                ('external_link', models.URLField(max_length=512, verbose_name='Ссылка')),
                ('photo', models.FileField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Название кейса (Ru)')),
                ('title_en', models.CharField(max_length=512, verbose_name='Название кейса (En)')),
                ('year', models.PositiveIntegerField(verbose_name='Год проведения')),
                ('body_ru', models.TextField(verbose_name='Описание (Ru)')),
                ('body_en', models.TextField(verbose_name='Описание (En)')),
                ('type_ru', models.CharField(choices=[(avantage_backend.blog.models.Case.TypeRU['INTERNAL'], avantage_backend.blog.models.Case.TypeRU['INTERNAL']), (avantage_backend.blog.models.Case.TypeRU['EXTERNAL'], avantage_backend.blog.models.Case.TypeRU['EXTERNAL'])], max_length=512, verbose_name='Тип кейса (Ru)')),
                ('type_en', models.CharField(choices=[(avantage_backend.blog.models.Case.TypeEN['INTERNAL'], avantage_backend.blog.models.Case.TypeEN['INTERNAL']), (avantage_backend.blog.models.Case.TypeEN['EXTERNAL'], avantage_backend.blog.models.Case.TypeEN['EXTERNAL'])], max_length=512, verbose_name='Тип кейса (En)')),
                ('show_on_main_page', models.BooleanField(default=False, verbose_name='Показывать на главной странице')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Название заказчика (Ru)')),
                ('name_en', models.CharField(max_length=512, verbose_name='Название заказчика (En)')),
                ('type_ru', models.CharField(max_length=512, verbose_name='Тип заказчика (Ru)')),
                ('type_en', models.CharField(max_length=512, verbose_name='Тип заказчика (En)')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Вложение кейса',
                'verbose_name_plural': 'Вложения кейсов',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.customer', verbose_name='Заказчик'),
        ),
    ]
