# Generated by Django 5.0.3 on 2024-03-23 09:07

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.FileField(upload_to=utils.files.upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='caseattachment',
            name='file',
            field=models.FileField(upload_to=utils.files.upload_path, verbose_name='Файл'),
        ),
    ]
