# Generated by Django 5.0.3 on 2024-04-14 09:55

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_photo_alter_caseattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="cover_image",
            field=models.FileField(
                null=True,
                upload_to=utils.files.upload_path,
                verbose_name="Файл",
            ),
        ),
        migrations.AddField(
            model_name="caseattachment",
            name="content_type",
            field=models.CharField(
                default="image", max_length=512, verbose_name="Тип содержимого"
            ),
        ),
    ]
