# Generated by Django 5.0.3 on 2024-04-14 11:07

import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_case_cover_image_caseattachment_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="cover_image",
            field=models.FileField(
                null=True,
                upload_to=utils.files.upload_path,
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="caseattachment",
            name="content_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                default="image",
                max_length=512,
                verbose_name="Тип содержимого",
            ),
        ),
    ]
