# Generated by Django 4.0.6 on 2024-04-25 22:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_case_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='body_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (En)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='body_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание (Ru)'),
        ),
    ]
