# Generated by Django 4.0.6 on 2024-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_case_body_en_alter_case_body_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='year',
            field=models.CharField(max_length=32, null=True, verbose_name='Год проведения'),
        ),
    ]
