# Generated by Django 4.0.6 on 2024-06-01 13:50

import avantage_backend.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_case_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер статьи'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер кейса'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_en',
            field=models.CharField(choices=[(avantage_backend.blog.models.Case.TypeEN['INTERNAL'], avantage_backend.blog.models.Case.TypeEN['INTERNAL']), (avantage_backend.blog.models.Case.TypeEN['EXTERNAL'], avantage_backend.blog.models.Case.TypeEN['EXTERNAL']), (avantage_backend.blog.models.Case.TypeEN['MICE'], avantage_backend.blog.models.Case.TypeEN['MICE'])], max_length=512, verbose_name='Тип кейса (En)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='type_ru',
            field=models.CharField(choices=[(avantage_backend.blog.models.Case.TypeRU['INTERNAL'], avantage_backend.blog.models.Case.TypeRU['INTERNAL']), (avantage_backend.blog.models.Case.TypeRU['EXTERNAL'], avantage_backend.blog.models.Case.TypeRU['EXTERNAL']), (avantage_backend.blog.models.Case.TypeRU['MICE'], avantage_backend.blog.models.Case.TypeRU['MICE'])], max_length=512, verbose_name='Тип кейса (Ru)'),
        ),
    ]
