# Generated by Django 5.0.6 on 2024-06-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_article_article_order_case_case_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["article_order"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["case_order"],
                "verbose_name": "Кейс",
                "verbose_name_plural": "Кейсы",
            },
        ),
    ]
