# Generated by Django 5.0.6 on 2024-06-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_article_options_alter_case_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.customer",
                verbose_name="Заказчик",
            ),
        ),
    ]
