# Generated by Django 5.0.3 on 2024-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_company_implemented_projects_company_interview_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="is_chief",
            field=models.BooleanField(default=False, verbose_name="Начальник"),
        ),
    ]
