# Generated by Django 5.0.3 on 2024-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0005_remove_award_place_award_place_en_award_place_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email_for_clients",
            field=models.CharField(
                max_length=1024, verbose_name="Email для клиентов"
            ),
        ),
    ]
