# Generated by Django 5.0.3 on 2024-04-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_company_email_for_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email_for_partners",
            field=models.EmailField(
                max_length=254, null=True, verbose_name="Email для СМИ"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email_for_mass_media",
            field=models.EmailField(
                max_length=254, verbose_name="Email для СМИ"
            ),
        ),
    ]
