# Generated by Django 5.0.3 on 2024-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_company_email_for_partners"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ok",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Одноклассники"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="vk",
            field=models.CharField(
                max_length=256, null=True, verbose_name="ВКонтакте"
            ),
        ),
    ]
