# Generated by Django 4.0.6 on 2024-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_ok_company_vk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='event',
            new_name='event_ru',
        ),
        migrations.AddField(
            model_name='award',
            name='event_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Мероприятие (En)'),
        ),
    ]
