# Generated by Django 4.0.6 on 2024-06-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_article_order_case_case_order_and_more'),
        ('core', '0010_rename_event_award_event_ru_award_event_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер награды'),
        ),
        migrations.AddField(
            model_name='award',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.case', verbose_name='Кейс'),
        ),
    ]
