# Generated by Django 4.0.6 on 2024-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_award_award_order_award_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='case',
        ),
        migrations.AddField(
            model_name='award',
            name='case_link',
            field=models.CharField(max_length=1024, null=True, verbose_name='Ссылка на кейс'),
        ),
    ]
