# Generated by Django 5.0.3 on 2024-03-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1, unique=True, verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Буква',
                'verbose_name_plural': 'Буквы',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('external_link', models.CharField(max_length=512)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.letter', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
