# Generated by Django 4.0.6 on 2024-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_letter_site_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='value',
            field=models.CharField(max_length=10, verbose_name='Буква'),
        ),
    ]
